server:
  port: 8080

spring:
  application:
    name: usersregistry

  datasource:
    url: jdbc:postgresql://172.18.0.1:5432/usersregistry
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#

