server:
  port: 8080

spring:
  application:
    name: users

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true

logging:
  level:
    root: debug
http:
  logging:
    enabled: false
    log-level: info
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#

