server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: restaurant
          uri: http://localhost:8081/
          predicates:
            - Path=/api/restaurants/**
        - id: cart
          uri: http://localhost:8082/
          predicates:
            - Path=/api/carts/**
        - id: user
          uri: http://localhost:8083/
          predicates:
            - Path=/api/users/**
        - id: address
          uri: http://localhost:8084/
          predicates:
            - Path=/api/address/**
        - id: food
          uri: http://localhost:8085/
          predicates:
            - Path=/api/foods/**



